name: React Native CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.19.0]

    steps:
    # 1. Чекаут кода
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Установка Node.js
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # 3. Кэш для npm
    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # 4. Удаляем старый package-lock.json, если он вызывает ошибки
    - name: Remove old lock file
      run: rm -f package-lock.json

    # 5. Установка зависимостей
    - name: Install dependencies
      run: |
        npm install
        npm update

    # 6. Запуск линтера
    - name: Run lint
      run: npm run lint

    # 7. Сборка Expo Web
    - name: Build Expo Web
      run: npx expo export:web
